### ISSUE TITLE
How can i use the repository?

### ISSUE THREAD

**Issue by dsp6414** [anwarminarso/MyRaspNet#2]
Is there any tutorial about the repository?

**Comment by anwarminarso** [comment]
Sorry I haven't had time to document yet. I'm focused on development. 
For installation/deployment you can read this guide
 [https://github.com/anwarminarso/MyRaspNet/wiki/Installation](url)
with this release
[https://github.com/anwarminarso/MyRaspNet/releases/download/v1.0.0-alpha.1/Publish.v1.0.0-alpha.zip](url)

**Comment by anwarminarso** [comment]
Feel free if you want to open this case again
